### ISSUE TITLE
This voice currently only supports LINEAR16 output.

### ISSUE THREAD

**Issue by sandglass14** [wavenet-for-chrome/extension#91]
"_Failed to synthesize text.
This voice currently only supports LINEAR16 output._"

I am using Wavenet for Chrome extension just to text-to-speech some text using voice Journey O. For some reason I get the above error. I was using that voice last week, everything was perfect. Now, all of a sudden the above error. The error seems to appear only for Journey voices, other listed voices work, but they are nowhere near the human-like quality of Journey voices, in my opinion.

Is there a way to resolve the above error somehow?

Appreciate any help. Thank you in advance.

**Comment by pgmichael** [comment]
Hello! This is an error message returned by Google itself. It means that the audio format asked for this voice isn't supported. I believe changing the playback or download audio format (ex: MP3, OGG) in the UI should fix the issue.

Let me know!

**Comment by superluig164** [comment]
It seems like Google changed something with the Journey voices.  Changing the output format to WAV should work, but now the error message says that these voices don't support pitch and speed adjustments.  They always didn't, but before they just did nothing, now it fails to read anything.

**Comment by sandglass14** [comment]
> It seems like Google changed something with the Journey voices. Changing the output format to WAV should work, but now the error message says that these voices don't support pitch and speed adjustments. They always didn't, but before they just did nothing, now it fails to read anything.

Yes, I believe you're right. The issue seems to stem from both Google and Wavenet. Google recently seems changed the audio encoding format for Journey voices, which might explain why pitch and speaking rate adjustments aren't supported for those voices yet. Unfortunately, switching the output format in Wavenet to WAV doesn't resolve the issue, resulting in this error:

"Failed to synthesize text. This voice does not support speaking rate or pitch parameters at this time."

For example, that's how currently JSON looks like in the official Google demo specifically for Journey voices (regardless how I change speech rate or pitch, it always passes the request with zero values for those settings for Journey voices): https://cloud.google.com/text-to-speech?hl=en
```
{
  "audioConfig": {
    "audioEncoding": "LINEAR16",
    "effectsProfileId": [
      "small-bluetooth-speaker-class-device"
    ],
    "pitch": 0,
    "speakingRate": 0
  },
  "input": {
    "text": "Movies, oh my gosh, I just just absolutely love them. They're like time machines taking you to different worlds and landscapes, and um, and I just can't get enough of it."
  },
  "voice": {
    "languageCode": "en-US",
    "name": "en-US-Journey-O"
  }
}
```

While WAV format should theoretically work for encoding format, but Wavenet extension UI does not allow to set speed to zero (the minimum allowed value is 0.5x). Maybe this is the reason for the generated error: ""Failed to synthesize text. This voice does not support speaking rate or pitch parameters at this time." ??? 

Is it something that Wavenet needs to fix asap?

**Comment by sandglass14** [comment]
So basically Journey speech voices are impossible to generate/download anymore using Wavenet for Chrome extension, rendering this extension pretty much useless (because all other voices in the list are just out right no go robot voices from 1970's), is that correct?
Thanks.

**Comment by sandglass14** [comment]
Hi there,

I’m pleased to notice that Journey voices are now working again in the Wavenet Chrome extension for the “When reading aloud” feature. To get it working, simply switch the audio format from default OGG to WAV.

However, Journey voices still **do not** function with the “When downloading” feature, which is a key point of this extension in my opinion. Currently, downloading is only supported in MP3 format. Please add support for downloading in WAV format to this feature.

Thank you!

**Comment by superluig164** [comment]
You also need to set the pitch and speed parameters back to 1x and 0,
otherwise you will still get the error that they are not supported with
Journey voices.

Thank you,
Tommy Sebestyen
